### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by ag-coder** [kigster/search-emlx-mailbox#1]
Hello kigster

i try to install your app but my install fails here:

> Installing nokogiri 1.6.8.1 with native extensions
> Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

i would like to use your app and search through my emlx archives.
thanks for help and sharing your app

**Comment by kigster** [comment]
@ag-coder Still need this app, or did you find an alternative?
